#!/usr/bin/perl
use strict;

##########################################################################

use CGI;

use lib "../perl";
use AUTH qw(%sessionDATA $sessionID getCookieSession resetPasswordRequest getUserID);
use HTML qw(print_html red_print);

##########################################################################

my $q = new CGI;

my $userID = getCookieSession();

redirection() if ($userID);

my $user = $q->param('user');

$userID = undef;
$userID = getUserID($user) if ($user);

if (!$user) {
	do_form();
} elsif ($userID) {
	# Form submitted, user exists
	resetPasswordRequest($user);
	print $q->header;
	print_html("header.html");
	print_html("password-sent.html");
	print_html("footer.html");
	exit;
	
} else {
	do_form("Username does not exist");
}

exit;



##########################################################################

sub do_form {
	my $error = shift;

	print $q->header;
	#print_html("header.html");

	my $html = print_html("forgot.html",'',1);
	if ($error) {
		$html =~ s/<!\@ERROR\@!>/$error<br\/>/gs;
	}
	print $html;

	#print_html("footer.html");
}

sub redirection {
	print "Location: https://edastro.com/\n\n";
}

##########################################################################


