#!/usr/bin/perl
use strict;

##########################################################################

use CGI;

use lib "../perl";
use AUTH qw(%sessionDATA $sessionID getCookieSession setCookieSession emailExists getUserID createUser resend_verify_email);
use ATOMS qw(btrim);
use HTML qw(print_html red_print);

##########################################################################

my $q = new CGI;

my $userID = getCookieSession();

if ($userID && !$sessionDATA{verified}) {
	resend_verify_email($userID,$sessionDATA{username},$sessionDATA{email});

	print $q->header;
	#print_html("header.html");
	my $html = print_html("email-resent.html",'',1);
	$html =~ s/<!\@EMAIL\@!>/$sessionDATA{email}<br\/>/gs;
	print $html;
	#print_html("footer.html");

} else {
	print "Location: https://edastro.com/\n\n";
}

exit;



##########################################################################

sub do_form {
	my $error = shift;

	print $q->header;
	#print_html("header.html");

	my $html = print_html("register.html",'',1);
	if ($error) {
		$html =~ s/<!\@ERROR\@!>/$error<br\/>/gs;
	}
	print $html;

	#print_html("footer.html");
}

##########################################################################


