#!/usr/bin/perl
use strict;

##########################################################################

use CGI;

use lib "../perl";
use AUTH qw(%sessionDATA $sessionID getCookieSession setCookieSession setPassword getUserFromResetCode getUserID getUserData invalidateResetCode);
use HTML qw(print_html red_print);

##########################################################################

my $q = new CGI;

my $userID = getCookieSession();
destroySession() if ($userID);

my $code  = $q->param('c');
my $pass1 = $q->param('pass');
my $pass2 = $q->param('pass2');

if ($code) {
	my $userID = getUserFromResetCode($code);
	my %user = ();
	%user = getUserData($userID) if ($userID);

	if (!$userID) {
		invalid_code('Invalid reset code');
	} elsif (!$pass1 && !$pass2) {
		do_form('',$user{username},$user{email},$code);
	} elsif ($pass1 ne $pass2) {
		do_form("Passwords do not match",$user{username},$user{email},$code);
	} elsif (!$pass1 || !$pass2) {
		do_form("Please enter new password twice",$user{username},$user{email},$code);
	} elsif ($userID && $user{email}) {
		setPassword($userID,$pass1);
		invalidateResetCode($code);
		print $q->header;
		print_html("/www/edastro.com/header.html");
		print_html("password-changed.html");
		print_html("/www/edastro.com/footer.html");
		exit;
	} else {
		invalid_code('Invalid reset code');
	}
	
} else {
	redirection();
}

exit;



##########################################################################

sub invalid_code {
	my $error = shift;

	print $q->header;
	#print_html("/www/edastro.com/header.html");

	my $html = print_html("invalid-code.html",'',1);
	if ($error) {
		$html =~ s/<!\@ERROR\@!>/$error<br\/>/gs;
	}
	print $html;

	#print_html("/www/edastro.com/footer.html");
}

sub do_form {
	my $error = shift;
	my $user  = shift;
	my $email = shift;
	my $code  = shift;

	print $q->header;
	#print_html("/www/edastro.com/header.html");

	my $html = print_html("resetpassword.html",'',1);
	$html =~ s/<!\@ERROR\@!>/$error<br\/>/gs;
	$html =~ s/<!\@USER\@!>/$user/gs;
	$html =~ s/<!\@EMAIL\@!>/$email/gs;
	$html =~ s/<!\@CODE\@!>/$code/gs;
	print $html;

	#print_html("/www/edastro.com/footer.html");
}

sub redirection {
	print "Location: https://edastro.com/auth/account\n\n";
}

##########################################################################


